# Generated by Django 4.2.7 on 2024-02-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoApp', '0003_imagesubmission_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_tag', models.CharField(max_length=100, unique=True)),
                ('backend_tag', models.CharField(max_length=100, unique=True)),
                ('image_submissions', models.ManyToManyField(related_name='image_tags', to='PhotoApp.imagesubmission')),
            ],
        ),
        migrations.AddField(
            model_name='imagesubmission',
            name='tags',
            field=models.ManyToManyField(related_name='submission_tags', to='PhotoApp.imagetag'),
        ),
    ]
